//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardStock
    {
        public int ID { get; set; }
        public int CardID { get; set; }
        public string CardNum { get; set; }
        public decimal Denomination { get; set; }
        public Nullable<int> InDetailID { get; set; }
        public Nullable<int> CancelDetailID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public int StockStatus { get; set; }
        public string StatusDescription { get; set; }
        public int LockStatus { get; set; }
        public int InStockPerson { get; set; }
        public System.DateTime InStockDateTime { get; set; }
        public int CardSortNum { get; set; }
        public int ThisDetailSortNum { get; set; }
        public int CardValidate { get; set; }
        public string CardOwner { get; set; }
        public Nullable<int> InStockFlag { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
