//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public string DeliveryMode { get; set; }
        public string DeliverModeDescription { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string Receiver { get; set; }
        public string ContactMethod { get; set; }
        public string DeliveryAddr { get; set; }
        public string DeliveryRemark { get; set; }
        public Nullable<int> SourceFlag { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
