//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int ID { get; set; }
        public string OrderNum { get; set; }
        public int OrderTaskId { get; set; }
        public int DeliveryTaskId { get; set; }
        public int ActivateTaskId { get; set; }
        public int OrderCreator { get; set; }
        public System.DateTime OrderCreatTime { get; set; }
        public int OrderStatus { get; set; }
        public string StatusDescription { get; set; }
        public int CustomerId { get; set; }
        public string CardType { get; set; }
        public int CardCount { get; set; }
        public decimal TotalAmount { get; set; }
        public string OrderProcStatus { get; set; }
        public decimal PayMoney { get; set; }
        public decimal HasPaidMoney { get; set; }
        public decimal HasReceivedMoney { get; set; }
        public int HasInvoice { get; set; }
        public decimal InvoiceMoney { get; set; }
        public string PayMode { get; set; }
        public string EntryCompany { get; set; }
        public string OutInvoiceCompany { get; set; }
        public int ActiveWay { get; set; }
        public int ProcPerson { get; set; }
        public int DeliveryMode { get; set; }
        public int DeliveryStatus { get; set; }
        public string DeliveryMan { get; set; }
        public Nullable<int> OrderCancelPerson { get; set; }
        public Nullable<System.DateTime> OrderCancelTime { get; set; }
        public int ActiveStatus { get; set; }
        public Nullable<int> ActivePerson { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public Nullable<int> OrderReceiver { get; set; }
        public Nullable<System.DateTime> ReceiveOrderTime { get; set; }
        public Nullable<int> SourceFlag { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
