//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMail
    {
        public int Id { get; set; }
        public int Sender { get; set; }
        public int Receiver { get; set; }
        public string MailContent { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public string MailType { get; set; }
        public int MailStatus { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<int> Reader { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
