//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProc
    {
        public int ID { get; set; }
        public string OrderNum { get; set; }
        public string ProcType { get; set; }
        public int ProcUser { get; set; }
        public System.DateTime ProcTime { get; set; }
        public string ProcRemark { get; set; }
        public string AllotFrom { get; set; }
        public string AllotTo { get; set; }
        public string AllotType { get; set; }
        public Nullable<int> SourceFlag { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
