//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProcDetail
    {
        public int ID { get; set; }
        public int MainID { get; set; }
        public int CardID { get; set; }
        public string CardStartNum { get; set; }
        public string CardEndNum { get; set; }
        public int CardCount { get; set; }
        public decimal CardDenomination { get; set; }
        public decimal CardTotalAmount { get; set; }
        public string AllotFrom { get; set; }
        public string AllotTo { get; set; }
        public string AllotType { get; set; }
        public string ProcType { get; set; }
        public Nullable<int> CardStockId { get; set; }
        public Nullable<int> SourceFlag { get; set; }
        public string SourceRemark { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
