//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHandle
    {
        public int ID { get; set; }
        public int TaskId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> FlowId { get; set; }
        public int FlowNodeId { get; set; }
        public Nullable<int> FlowNodeSite { get; set; }
        public string Handler { get; set; }
        public System.DateTime HandleTime { get; set; }
        public string HandleStatus { get; set; }
        public string HandleStatusDescription { get; set; }
        public string HandleRemark { get; set; }
        public string NextHandler { get; set; }
        public string LastHandler { get; set; }
        public Nullable<int> LeapFlag { get; set; }
        public int IsDel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
