//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string UserAccount { get; set; }
        public string Pwd { get; set; }
        public string UserName { get; set; }
        public string Telephone { get; set; }
        public string MobilePhone { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string JobNumber { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string JobStatus { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public int DepartmentId { get; set; }
        public int RoleId { get; set; }
        public int PauseReceive { get; set; }
        public string InLinePhone { get; set; }
        public string UserRemark { get; set; }
        public int IsDel { get; set; }
        public string Remark { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Revisor { get; set; }
        public Nullable<System.DateTime> ReviseTime { get; set; }
    }
}
